### ISSUE TITLE
feeat: criar organização

### ISSUE THREAD

**Issue by RodrigoNet0** [GustavoSantoz/curso-fullstack-gt02#1]
Criar a organização e adicionar os membros

**Comment by GustavoSantoz** [comment]
Estou vendo com o professor Kelvys e David para ver como vai ser feito a organização ou se vai ser abordado por agora o contexto de organização e um trabalho em grupo dentro de um só projeto.

**Comment by RodrigoNet0** [comment]
Ok!

**Comment by GustavoSantoz** [comment]
Como pedido anteriormente foi criado a organização para a turma Geração Tech 02. 

[Organização GTech-02](https://github.com/gtech-02)
